### ISSUE TITLE
tools/delete_imaging_upload.pl

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris-MRI#1067]
- [ ] Test deletion of an entire MRI upload (UploadID) with SQL and file backup (ensure the SQL and file backup repopulate the database correctly after the deletion) 
  - default file generated, and sourced back without issue.
- [x] Test deletion of an UploadID that has the same TarchiveID as an other UploadID - this should fail with an error message explaining there are multiple UploadID for a given TarchiveID
  - update tarchiveID for an UploadID in table mri_upload with another existing. Run the script, failed.
- [x] Test deletion of an UploadID with QC information attached - this should fail with proper error message
- [ ] Test deletion of an UploadID with a parameter_form filled and the option `-form` and ensure the entries in the parameter form have been deleted
- [ ] On a defaced dataset, test running the delete script with the `-defaced` option - this should delete only non-defaced MINC files for that UploadID
  - cannot find a defaced dataset. 
- [ ] Run the delete script with option `-basename <FileBaseName>` specifying a basename for the MINC files to be deleted - only images matching that basename should be deleted for the UploadID

Bugs found:
- https://github.com/aces/Loris-MRI/issues/1107

**Comment by CamilleBeau** [comment]
The checked steps ran as expected, the rest I believe are impacted by [this issue](https://github.com/aces/Loris-MRI/issues/1107), so I will continue testing when resolved!
