### ISSUE TITLE
dicom_archive/get_dicom_info.pl

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris-MRI#1075]
- [x] test the different options of the script and ensure it works as expected

**Comment by MaximeMulder** [comment]
This seems to be working but I did not manage to test the -stdin option. Did I do it wrong ?

```
(loris-mri-python) lorisadmin@mmulder-test-26:/data/testing$ /opt/Loris-MRI/bin/mri/dicom-archive/get_dicom_info.pl -image -stdin < ImagingUpload-13-42-zcoZR0/MR.X.1.2.276.0.7230010.3.1.4.0.30.1243441413.5527.dcm
xargs: WARNING: a NUL character occurred in the input.  It cannot be passed through in the argument list.  Did you mean to use the --null option?
(loris-mri-python) lorisadmin@mmulder-test-26:/data/testing$
```

In the greater scheme of things, is this script still used nowadays ? It seems to me that we can achieve the same outcome with the DICOM toolkit and the Pydicom library.

**Comment by MaximeMulder** [comment]
Okay, I just needed to pass the name in the stdin and wait a little bit, so it works !
