### ISSUE TITLE
dicom_archive/dicomTar.pl and dicom_archive/updateMri_upload.pl

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris-MRI#1076]
- [x] run dicomTar.pl without the -database flag and ensure nothing gets inserted into the DB
- [x] run dicomTar.pl with the -database flag and check that entries got inserted into the DB in the tarchive* tables correctly
- [x] run dicomTar.pl with the -mri_upload_update flag on a DICOM directory that was not previously uploaded via the imaging uploader (ensure there is nothing in mri_upload table for that study before running the script) => ensure that an entry has been added to mri_upload for the uploaded DICOM study

**Comment by MaximeMulder** [comment]
This seems to be working but I did not manage to test the `-stdin` option. Did I do it wrong ?

```
(loris-mri-python) lorisadmin@mmulder-test-26:/data/testing$ /opt/Loris-MRI/bin/mri/dicom-archive/get_dicom_info.pl -image -stdin < ImagingUpload-13-42-zcoZR0/MR.X.1.2.276.0.7230010.3.1.4.0.30.1243441413.5527.dcm                                                                                                        xargs: WARNING: a NUL character occurred in the input.  It cannot be passed through in the argument list.  Did you mean to use the --null option?
(loris-mri-python) lorisadmin@mmulder-test-26:/data/testing$
```

In the greater scheme of things, is this script still used nowadays ? It seems to me that we can achieve the same outcome with the DICOM toolkit and the Pydicom library.
