### ISSUE TITLE
CentOS Server Installation of Loris-MRI

### ISSUE THREAD

**Issue by dyt811** [aces/Loris-MRI#139]
Hi, noob question about "imaging_install.sh". Since it calls apt-get for dicomtk and so it seems dicomtk is not available via Yum. Any tips for CentOS installations stuck at this stage? Any possibility to update the Readme to include suggestions to get around it? Thanks.

**Comment by christinerogers** [comment]
Thanks for your question -- We'll definitely be updating steps 3 and 4 in the Loris-MRI Readme for our next release with the following info for CentOS installs:

(Step 3) Download and install MINC toolkit for CentOS:  
```
wget http://packages.bic.mni.mcgill.ca/minc-toolkit/RPM/minc-toolkit-1.0.08-20160205-CentOS_6.7-x86_64.rpm
sudo rpm -Uvh ~/minc-toolkit-1.0.08-20160205-CentOS_6.7-x86_64.rpm 
```

(Step 4)  Download and install DICOM toolkit, starting with the dependency _CharLS_
```
sudo yum -y install CharLS
wget http://tissuestack.org/downloads/CentOS/dcmtk-3.6.0-0.el6.x86_64.rpm
sudo rpm -i -v dcmtk-3.6.0-0.el6.x86_64.rpm
```

Then continue to follow the instructions in the Loris-MRI Readme, including running the _imaging_install.sh_ script.  (Note that aspects of the script were designed for Ubuntu, so some error messages will be encountered such as on the apt-get statement.)

**Comment by dyt811** [comment]
Cool. Thanks. That did the trick and I was able to step through most of the rest of the setup. Going to test more and see.
