### ISSUE TITLE
"SliceTiming" values are in milliseconds instead of seconds

### ISSUE THREAD

**Issue by PierreEMorin** [aces/Loris-MRI#377]
I got this mail from Hanad Sharmarke (Pierre Bellec lab).  Briefly, Hanad put the previous BIDS release through a BIDS validator and it failed because the "SliceTiming" values are in milliseconds instead of seconds.

> Hello,
> 
> Regarding the bids release that was done in the summer, I put it through a bids validator using this website. I found that the slice timing correction is not in seconds.
> 
> https://bids-standard.github.io/bids-validator/
> 
> Hanad
> 
> image.png
![image](https://user-images.githubusercontent.com/6494031/51861357-f85c7f00-2309-11e9-871e-a033344552dd.png)

**Comment by cmadjar** [comment]
PR merged.
