### ISSUE TITLE
Investigate on how to reduce the size of parameter_file

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris-MRI#388]
Several options were given during the imaging meeting of February 1st, 2019:

Investigate those two possibilities to try to reduce the size of the `parameter_file` table:
1. Look at the content of the `parameter_file` table and evaluate which parameters/ MINC headers are unnecessary
2. Could convert the numbers in int or decimals instead of storing in string (would need to add a column to store that) Not sure how much space we would save though.

**Comment by cmadjar** [comment]
### First investigation on the fields present in `parameter_file`:

[see this spreadsheet for details](https://docs.google.com/spreadsheets/d/1dckNfwaPqEIukgnIAubAsIhTqZdUDkTBPEvTnj-JcEo/edit#gid=0)

- **46 fields are being duplicated in the table** (see fields with Comment = "duplicated ..." in the spreadsheet)
- **38 fields that are probably not interesting to store in the table** (see fields with Comment = "not interesting" in the spreadsheet)
- **about 400 fields that start with `dicom_0x...`** where we have no idea what they stand for (see fields with Comment = "?????? not mapped in mapDicomParameters" in the spreadsheet)
- **header field should probably be removed since it forces us to use `longtext` instead of `varchar` in `parameter_file`**

=> **left with 385 fields either not duplicated or not obscure** (not all being necessarily present in a given MINC file)

### Preliminary tests on my sandbox: 

- removal of the header, the duplicated and the not interesting values deleted about 20% of the rows
```
delete from parameter_file_on_a_diet WHERE ParameterTypeID IN (SELECT ParameterTYpeID from parameter_type where Name IN ('rootvariable:children','rootvariable:parent','rootvariable:varid','rootvariable:vartype','rootvariable:version','image_time','inversion_time','sar','echo_train_length','number_of_averages','percent_phase_field_of_view','percent_sampling','pixel_bandwidth','repetition_time','slice_thickness','window_center','study:field_value','study_id','xspace','xstep','yspace','ystart','zspace','acquisition_time','echo_time','mr_acquisition_type','phase_encoding_direction','protocol_name','receiving_coil','sequence_name','series_description','series_time','transmitting_coil','window_width','patient_dob','patient_name','patient_id','patient_position','patient_sex','manufacturer_model_name','institution_name','manufacturer','study_description','device_serial_number','software_versions','dicom_0x0008:el_0x1010','xstart','ystep','zstep','acquisition:vartype','dicominfo:vartype','image:vartype','patient:vartype','study:vartype','acquisition:varid','image:varid','max:varid','min:varid','patient:varid','study:varid','xspace:varid','yspace:varid','zspace:varid','acquisition:version','image:version','max:version','min:version','patient:version','study:version','xspace:version','yspace:version','zspace:version','dicominfo:varid','header','number_of_phase_encoding_steps','study_time'));
```
- removal of the `dicom_0x*` values deleted about 35% of the rows
```
delete from parameter_file_on_a_diet WHERE ParameterTypeID IN (SELECT ParameterTYpeID from parameter_type where Name like "dicom_0x%");
```
- since the header value was removed, converted the `Value` field of `parameter_type` back to `varchar(255)`

=> decreasing the number of rows in `parameter_file` by about 55%
=> decreased the size of `parameter_file` of about XXX ???  (need to ask the sys admin for the size of the table before and after the diet)

### Left to do for the investigation

- [ ] figure out in the dicom* fields if any are interesting. If they are, then map them to a new field like it is done in the function `mapDicomParameters` present in `MRI.pm`. Chances are they are not relevant.
- [ ] bring that up at the next imaging meeting again with some stats so we can take an informed decision

**Comment by davidblader** [comment]
CCNA Stats:

 - **Currently** 
*(4191.20 MB)*
```
           Rows: 3435512
 Avg_row_length: 1215
    Data_length: 4176101376
Max_data_length: 0
   Index_length: 218693632
      Data_free: 49283072
 Auto_increment: 2415468
```
 - **After running the first deletion query:**
```
delete from parameter_file_on_a_diet WHERE ParameterTypeID IN (SELECT ParameterTYpeID from parameter_type where Name IN ('rootvariable:children','rootvariable:parent','rootvariable:varid','rootvariable:vartype','rootvariable:version','image_time','inversion_time','sar','echo_train_length','number_of_averages','percent_phase_field_of_view','percent_sampling','pixel_bandwidth','repetition_time','slice_thickness','window_center','study:field_value','study_id','xspace','xstep','yspace','ystart','zspace','acquisition_time','echo_time','mr_acquisition_type','phase_encoding_direction','protocol_name','receiving_coil','sequence_name','series_description','series_time','transmitting_coil','window_width','patient_dob','patient_name','patient_id','patient_position','patient_sex','manufacturer_model_name','institution_name','manufacturer','study_description','device_serial_number','software_versions','dicom_0x0008:el_0x1010','xstart','ystep','zstep','acquisition:vartype','dicominfo:vartype','image:vartype','patient:vartype','study:vartype','acquisition:varid','image:varid','max:varid','min:varid','patient:varid','study:varid','xspace:varid','yspace:varid','zspace:varid','acquisition:version','image:version','max:version','min:version','patient:version','study:version','xspace:version','yspace:version','zspace:version','dicominfo:varid','header','number_of_phase_encoding_steps','study_time'));
```
*(4187.44 MB)*

```
           Rows: 1724106
 Avg_row_length: 2418
    Data_length: 4169416704
Max_data_length: 0
   Index_length: 217219072
      Data_free: 31457280
 Auto_increment: 2415468
```

 - **After running the second deletion query:**
`delete from parameter_file_on_a_diet WHERE ParameterTypeID IN (SELECT ParameterTYpeID from parameter_type where Name like "dicom_0x%");`

*(3931.05 MB)*

```
           Rows: 1914630
 Avg_row_length: 2042
    Data_length: 3911467008
Max_data_length: 0
   Index_length: 211877888
      Data_free: 251658240
 Auto_increment: 2415468
```
i have no idea how there are now ~200,000 new rows after running a delete query... but the table did decrease in size. very weird. also did not get as substantial of a size reduction.

**Comment by nicolasbrossard** [comment]
IBIS Stats:

 - **Currently** 
*(3657.98 MB)*
```
           Rows: 13026904
 Avg_row_length: 230
    Data_length: 3007315968
Max_data_length: 0
   Index_length: 828358656
      Data_free: 6291456
 Auto_increment: 10790179
```
 - **After running the first deletion query:**
```
delete from parameter_file_on_a_diet WHERE ParameterTypeID IN (SELECT ParameterTYpeID from parameter_type where Name IN ('rootvariable:children','rootvariable:parent','rootvariable:varid','rootvariable:vartype','rootvariable:version','image_time','inversion_time','sar','echo_train_length','number_of_averages','percent_phase_field_of_view','percent_sampling','pixel_bandwidth','repetition_time','slice_thickness','window_center','study:field_value','study_id','xspace','xstep','yspace','ystart','zspace','acquisition_time','echo_time','mr_acquisition_type','phase_encoding_direction','protocol_name','receiving_coil','sequence_name','series_description','series_time','transmitting_coil','window_width','patient_dob','patient_name','patient_id','patient_position','patient_sex','manufacturer_model_name','institution_name','manufacturer','study_description','device_serial_number','software_versions','dicom_0x0008:el_0x1010','xstart','ystep','zstep','acquisition:vartype','dicominfo:vartype','image:vartype','patient:vartype','study:vartype','acquisition:varid','image:varid','max:varid','min:varid','patient:varid','study:varid','xspace:varid','yspace:varid','zspace:varid','acquisition:version','image:version','max:version','min:version','patient:version','study:version','xspace:version','yspace:version','zspace:version','dicominfo:varid','header','number_of_phase_encoding_steps','study_time'));
```
*(6028.98)*

```
           Rows: 5756443
 Avg_row_length: 940
    Data_length: 5413797888
Max_data_length: 0
   Index_length: 908050432
      Data_free: 52428800
 Auto_increment: 10790179
```

 - **After running the second deletion query:**
`delete from parameter_file_on_a_diet WHERE ParameterTypeID IN (SELECT ParameterTYpeID from parameter_type where Name like "dicom_0x%");`

*(5984.17)*

```
           Rows: 3290544
 Avg_row_length: 1645
    Data_length: 5413797888
Max_data_length: 0
   Index_length: 861061120
      Data_free: 60817408
 Auto_increment: 10790179
```
Like David, I observed an **increase** in the table size after the delete...

**Comment by cmadjar** [comment]
@nicolasbrossard @davidblader are your create table statement identical between the two tables? I noticed that if the indexes and foreign keys are not present in the copied table, then it gets way bigger. So when comparing the tables, make sure all the indexes and foreign key are identical between the two tables. Adding the foreign keys significantly decreases the size of the table.

Could you retry after making sure that `parameter_file` and `parameter_file_on_a_diet` have the same `create table` structure?

**Comment by davidblader** [comment]
updated my comment to show correct, most recent results of deletion queries

**Comment by cmadjar** [comment]
PREVENT-AD Stats:

 - **Currently** 
*(4844.00 MB)*
```
           Rows: 19542209
 Avg_row_length: 197
    Data_length: 3852468224
Max_data_length: 0
   Index_length: 1226833920
      Data_free: 24589107200
 Auto_increment: 20694886
```
 - **After running the first deletion query:**
```
delete from parameter_file_on_a_diet WHERE ParameterTypeID IN (SELECT ParameterTYpeID from parameter_type where Name IN ('rootvariable:children','rootvariable:parent','rootvariable:varid','rootvariable:vartype','rootvariable:version','image_time','inversion_time','sar','echo_train_length','number_of_averages','percent_phase_field_of_view','percent_sampling','pixel_bandwidth','repetition_time','slice_thickness','window_center','study:field_value','study_id','xspace','xstep','yspace','ystart','zspace','acquisition_time','echo_time','mr_acquisition_type','phase_encoding_direction','protocol_name','receiving_coil','sequence_name','series_description','series_time','transmitting_coil','window_width','patient_dob','patient_name','patient_id','patient_position','patient_sex','manufacturer_model_name','institution_name','manufacturer','study_description','device_serial_number','software_versions','dicom_0x0008:el_0x1010','xstart','ystep','zstep','acquisition:vartype','dicominfo:vartype','image:vartype','patient:vartype','study:vartype','acquisition:varid','image:varid','max:varid','min:varid','patient:varid','study:varid','xspace:varid','yspace:varid','zspace:varid','acquisition:version','image:version','max:version','min:version','patient:version','study:version','xspace:version','yspace:version','zspace:version','dicominfo:varid','header','number_of_phase_encoding_steps','study_time'));
```
*(4843.30 MB)*

```
            Rows: 12514843
 Avg_row_length: 307
    Data_length: 3852075008
Max_data_length: 0
   Index_length: 1226473472
      Data_free: 24343740416
 Auto_increment: 20694886
```

 - **After running the second deletion query:**
`delete from parameter_file_on_a_diet WHERE ParameterTypeID IN (SELECT ParameterTYpeID from parameter_type where Name like "dicom_0x%");`

*(MB)*

```
 
```

**Comment by cmadjar** [comment]
### Summary:

| _Project_ | _% reduction in table size in MySQL_ | _% reduction in number of rows_ |
| --------- | ------------------------------------- | -------------------------------- |
| **CCNA** | 5% | 32% |
| **IBIS** | ? | 74% |
| **PREVENT-AD** | 2% | 46% |

Note: MySQL dump size for RB dataset:
- 146 MB originally
- after removal of the `header` rows, became 15 MB
- after removal of the duplicated header rows (first query above) 3.8MB
- after removal of the `dicom_0x%` headers: 2.1MB

**Comment by cmadjar** [comment]
Decision taken during the imaging meeting of July 4th, 2019:

Remove the `header` rows from the `parameter_file` table and convert back the `Value` field to `text`.

We can always remove more later if needed.

**Comment by cmadjar** [comment]
Both PRs merged so closing the issue.
