### ISSUE TITLE
Visit label not validated by the MRI pipeline

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris-MRI#410]
This was reported by Jessica from CCNA. Someone defined the patient name in the DICOM headers of an uploaded file to be PSCID_CANDID_VLABEL, where both PSCID and CANDID exist and are valid but where VLABEL is not a valid existing visit label. Since the prod file in CCNA has 'createVisitLabel' set to 1, the pipeline proceeded to create this invalid visit label...The pipeline should always validate the visit label before creating it.

**Comment by cmadjar** [comment]
PR to fix this was merged on 20.3.
