### ISSUE TITLE
New features to add to the imaging delete script

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris-MRI#412]
Add these features to `delete_imaging_upload.pl`:

1. Add an option to generate a file that will contain the MySQL `INSERT` statements that can be used to restore the state of the tables to what it was before the deletions.
2. Add an option to specify the set of modalities/scan types to delete. The script will only delete the MINC files associated to those modalities and anything that was obtained using these MINC files.
3. Add an option such that when deleting a MINC file, the processed data associated to it in `files` is kept while the data in `files_intermediary` is deleted: the script will set the `SourceFileID` in table `files` for these processed files to `NULL` and also set the `TarchiveSource` to the same `TarchiveID` that the original MINC file had.

**Comment by cmadjar** [comment]
PR merged.
