### ISSUE TITLE
Move imaging scripts outside of /data

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris-MRI#479]
Only data should go into `/data/`. Imaging scripts (namely the `/data/$PROJ/bin/mri/` directory) should be moved somewhere that makes more sense.

**Comment by cmadjar** [comment]
@christinerogers The imaging scripts could be run from anywhere (I am running them on a different directory on my Mac). All that is left here is to decide where we could suggest to install the imaging pipeline. Then, we'll need to change the documentation and the install script. Feels like this could be another good job for a google season of code student if we have some.

**Comment by driusan** [comment]
If they can go anywhere why aren't they just placed in your `$PATH`?

**Comment by cmadjar** [comment]
@driusan I am not sure I understand fully your question. In theory, `$PATH` can be empty before you do the install. But indeed, we do use bash variables in the environment files mixed with Config DB variables to specify where the MRI code is installed.

Note: by default, the install script is still installing the MRI code in `/data/<project>/bin/mri` but the beauty of having the code able to be installed anywhere makes it so that it can be moved away from the `/data` directory

**Comment by driusan** [comment]
I don't understand.. how could `$PATH` be empty?

**Comment by cmadjar** [comment]
I remember having seen that on some system but don't remember the details.

**Comment by cmadjar** [comment]
The verdict for the new place for the LORIS-MRI data would be `/opt` as discussed during a roadmap meeting.

**Comment by christinerogers** [comment]
@cmadjar can @vietdhoang update the documentation on this one?  markdowns included.

**Comment by cmadjar** [comment]
sure!
