### ISSUE TITLE
Stricter checks in mri_protocol table to determine the types of scan

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris-MRI#488]
When the MRI pipeline processes a particular scan, it tries to match the scan properties with
a line in the mri_protocol table in order to determine the scan type, stopping as soon as a match
is found. But what if there is more than one line that matches? This is a clear indication that the mri_protocol
has not been setup properly.

When scanning, all the lines of mri_protocol should be read and the algorithm should make sure that at most
one line matches the current scan. If there is more than one match, the scan should not be inserted and an error
should be reported.

Original Redmine ticket: https://redmine.cbrain.mcgill.ca/issues/13799

**Comment by cmadjar** [comment]
Closing this issue as this was done in #596.
