### ISSUE TITLE
[install] improve error handling for db, mkdir incoming/,  distro detection 

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris-MRI#498]
Things to error-proof in the imaging installer, based on recent feedback, e.g. from Sotirios -- 

- [x] check whether `/data/incoming/` was actually created ([L123](https://github.com/aces/Loris-MRI/blob/minor/imaging_install.sh#L123)) - if not, print message about what commands to run. this happens from time to time (user unable to create new subdirectories right under `/data`

- [x] check whether database connection works - Else abort with a useful error message if can't connect (e.g. password typo)

- [x] improve handling of distro detection, per @PapillonMcGill [Loris-Core #4113](https://github.com/aces/Loris/pull/4113/files) (RM 12834)
Apply the following to imaging_install.sh for more robust detection of the distribution  -- 

```

Detecting distribution
os_distro=$(hostnamectl |awk -F: '/Operating System:/{print $2}'|cut -f2 -d ' ')
debian=("Debian" "Ubuntu")
redhat=("Red" "CentOS" "Fedora" "Oracle")

if [[ " ${debian[*]} " =~ " $os_distro " ]]; then
...
elif [[ " ${redhat[*]} " =~ " $os_distro " ]]; then
...
fi
```

**Comment by cmadjar** [comment]
I think we can close this issue. @christinerogers @vietdhoang do you agree?
