### ISSUE TITLE
Pipeline fails to run with createCandidate set to 1

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris-MRI#522]
When running `imaging_upload_file.pl` on an archive for a candidate that does not exist and with the config setting `createCandidate` set to 1, if fails, complaining about trying to create a candidate that already exists. Here's what happens:

* `imaging_upload_file.pl` calls `tarchiveLoader`, which calls `MRIProcessingUtilities::determineSubjectID`, which will create the non-existent candidate.
* `imaging_upload_file.pl` then calls `minc_insertion.pl`, which also calls `MRIProcessingUtilities::determineSubjectID`, except this time it will try to create a candidate that already exists and dies with an error message.

**Comment by cmadjar** [comment]
This was fixed for release 22 by https://github.com/aces/Loris-MRI/pull/573/files

Note that as of 23.0, the code has been refactored and the issue does happen anymore.
