### ISSUE TITLE
[minc_insertion.pl] Missing entries in notification_spool

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris-MRI#541]
When the pipeline attempts to create a visit in order to insert a scan and the visit could not be created because the project ID/subproject ID specified in the `prod` file are invalid, there should be an entry in table `notification_spool` indicating exactly why the session was not created (project ID invalid, no such subproject X for project Y, etc...) There are currently no such logs.

**Comment by cmadjar** [comment]
@nicolasbrossard Looks like this was fixed and merged so closing the issue. Feel free to reopen if I misunderstood.
