### ISSUE TITLE
Script bids_import.py should associate files to a project

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris-MRI#548]
When importing files with `bids_import.py`, the user should have to specify what project the files should be associated with. This is to make sure that they appear in the imaging browser, which filters out the files not associated with any project (see `DataFrameworkMenu::getDataProvisionerWithFilters()` and `UserProjectMatch`)

**Comment by cmadjar** [comment]
This should have been resolved by https://github.com/aces/Loris-MRI/pull/558/files. @laemtl if you disagree, feel free to reopen the issue.
