### ISSUE TITLE
[wiki migration] Update docs in this repo to point to the markdowns instead of the Loris wiki

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris-MRI#562]
Update links in this repo to point to the new loris markdowns instead of the Loris wiki
can be done anytime before release 24, not more urgent than that since the markdown/migration is still in progress.

**Comment by cmadjar** [comment]
@christinerogers will we have season of docs students? If so, could this be added to their possible tasks?

**Comment by christinerogers** [comment]
Yes, this will be great and I'll know more if we're getting a writer within the next 5 weeks 👍

**Comment by christinerogers** [comment]
I believe most of the updates would point to docs on this branch - not merged yet : 
https://github.com/aces/Loris/pull/6910
