### ISSUE TITLE
Release Notes to be updated

### ISSUE THREAD

**Issue by jesscall** [aces/Loris-MRI#574]
The following error was experienced by myself and Alfredo:

```
Can't locate object method "selectall_array" via package "DBI::db" at /data/ccna/bin/mri/uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm line 1819.
```

The issue can be fixed by simply upgrading the `DBI` dependency to the latest version since  the method `selectall_array` isn't available before DBI version 1.635. [[Reference]](https://metacpan.org/pod/DBI#selectall_array)

Can update using this command:
`cpan DBI`

I should note, this should **not** be an issue for new MRI installs.

**Comment by cmadjar** [comment]
This has been added to the release notes of 22.0.0 which is where the issue came up. Thank you @jesscall for reporting the issue!
