### ISSUE TITLE
[bids_import] file_parameters value too long to be inserted into database

### ISSUE THREAD

**Issue by ycAbout** [aces/Loris-MRI#589]
In importing bids dataset, in inserting nifti files:
Insert query failure: (1406, "Data too long for column 'Value' at row 1")
Seems that some field of file_parameters have too long values.
Still investigating what happened, will update when there is progress.

@gdevenyi

**Comment by ycAbout** [comment]
Update:
The cause has been found.
In the bids sample, there is a file_parameter field has a length 69032, suppose to be inserted as Value column into parameter_file table. However the value has a text datatype, holds up to 65535 characters, causing the error.

It is a more complicated issue when you look into the history:

History of parameter_file Value column datatype change:
2017, v18, it was changed to [longtext](https://github.com/aces/Loris/blob/11e6780c0d0e2f4e33ee915f8258f9222c314892/SQL/Archive/18.0/2017-06-22_parameter_file_LONGTEXT.sql)
2019, v22, it was changed back to [text](https://github.com/aces/Loris/blob/11e6780c0d0e2f4e33ee915f8258f9222c314892/SQL/Archive/22.0/2019-07-04-remove_header_row_from_parameter_file_and_convert_back_to_Value_field_to_text.sql)
[see also 21.0_to_22.0 upgrade](https://github.com/aces/Loris/blob/11e6780c0d0e2f4e33ee915f8258f9222c314892/SQL/Release_patches/21.0_To_22.0_upgrade.sql)
so far in sql schema [0000-00-00-schema.sql](https://github.com/aces/Loris/blob/main/SQL/0000-00-00-schema.sql), it is still longtext
Either way, there is something wrong.

Solution:
Option 1. in bids import and related database libraries, filter out information longer than 65535 characters, then insert. Change 0000-00-00-schema.sql
Option 2. Alter parameter_file Value to be longtext. add a sql patch.

I vote for option 2. I can make a PR.
However, please bring related persons to discuss about it.
@cmadjar 

cc
@gdevenyi

**Comment by gdevenyi** [comment]
What do the contents of such a field look like?

**Comment by ycAbout** [comment]
> What do the contents of such a field look like?

This file is an example:
[sub-DIC0001_ses-V01_T2w.txt](https://github.com/aces/Loris-MRI/files/6031976/sub-DIC0001_ses-V01_T2w.txt)

There maybe other similar cases.

**Comment by gdevenyi** [comment]
Thanks.

From my view I'd find it very hard to decide what can be removed vs not in that file. I'd prefer everything be inserted.

**Comment by cmadjar** [comment]
@ycAbout very sorry for the delay... Have you tried converting the Value in parameter_file to long text in the end? Did that fix your issue? I would probably go for that solution if that works.

Otherwise, you could always filter out parameters that are too long to be inserted into parameter_file indeed. Note: not inserting a field into parameter_file means you will not be able to query that field, however, the information will remain available in the file.

I would try first to change the column type in the database.

**Comment by ycAbout** [comment]
@cmadjar 
I tried to change it longtext in sql and it worked. Just was waiting for you input, given there was some back and forth around this issue in history. Now I can make a PR to LORIS.

**Comment by ycAbout** [comment]
I think the PR has been merged and this issue can be closed :) @cmadjar

**Comment by cmadjar** [comment]
Perfect! Thank you @ycAbout :)
