### ISSUE TITLE
[bids_import] add bids validator to bids import

### ISSUE THREAD

**Issue by ycAbout** [aces/Loris-MRI#591]
Gabriel @gdevenyi raised the question, which seems reasonable to me as well.

Bids validator can be added as one of the first steps before actually processing the data.

https://github.com/bids-standard/bids-validator

**Comment by cmadjar** [comment]
@ycAbout and @gdevenyi The BIDSLayout library always check by default if the files are BIDS compliant: https://bids-standard.github.io/pybids/generated/bids.layout.BIDSLayout.html

https://github.com/aces/Loris-MRI/blob/72146eb865ccee415787411e79e6ebee5c5bfd0e/python/lib/bidsreader.py#L86

So I don't think you need an extra call to the bids-validator. It will duplicate the work and add processing time for no reason. Unless there is something that I am missing?

Let me know.

**Comment by gdevenyi** [comment]
The BIDSLayout reader does do some validation, but it does not appear to be at the same level as the bids-validator:
https://github.com/bids-standard/bids-validator

**Comment by ycAbout** [comment]
I think both of you are right.

The BIDSLayout library indeed has a `validate` parameter default to be true. 
However, 
Initially I test the import using a invalid bids data set (invalid according to https://github.com/bids-standard/bids-validator), it did not report anywhere that it is an invalid bids data set.
I re-tested it used another invalid bids data set (invalid according to https://github.com/bids-standard/bids-validator) today, where I added random character (e.g., run) in random place in individual file naming, it did not report anywhere it is invalid data set, but rather other errors, resulting from empty result from bids_layout.

Having said above, I do not think this is a live or die issue, but rather an optimization issue.
