### ISSUE TITLE
Incorporating support for animal MRIs

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris-MRI#592]
This has been brought up during the brainstorming session for the 5-year LORIS roadmap.

@ycAbout working on this?

**Comment by ycAbout** [comment]
Yes, I mentioned it and I am working on it :)

cc:
@gdevenyi

**Comment by gdevenyi** [comment]
The recent BIDS import bugs fixed by @ycAbout are in preparation use with a bruker-to-bids tool for animal images. (dcm2mnc is not usable because the DICOMS bruker produces are not-standards compliant).
