### ISSUE TITLE
Detect ambiguous mri_protocol settings at runtime

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris-MRI#596]
The MRI pipeline should detect whether the constraints specified in the `mri_protocol` table can identify a given scan as being of more than one type. For example if the `mri_protocol` table states that a scan with a `TI` between 1000 and 2000 is a `T1` and a scan with a `TR` between 2500 and 3000 is a `T2`, then a scan that has **both** 1000 <= T1 <= 2000 and 2500 <= TR <= 3000 could be either a `T1` or a` T2`, depending on which line of the `mri_protocol` table is used first to perform the scan type identification. Instead, _all_ lines of the `mri_protocol` table should be used to identify a scan and the pipeline should report when different lines give different results. In such cases, a warning should be emitted and the scan should be identified as 'Unknown'.

Related to #477

**Comment by cmadjar** [comment]
Possibly related to #363 and #477

**Comment by nicolasbrossard** [comment]
@cmadjar Definitely related to #477 but not #363 IMHO.

**Comment by cmadjar** [comment]
@nicolasbrossard thank you! I updated the description to add the link to #477

**Comment by cmadjar** [comment]
@nicolasbrossard is that the same thing as #488?

**Comment by nicolasbrossard** [comment]
@cmadjar Yep, these basically describe the same feature request.

**Comment by cmadjar** [comment]
OK. Closing this one in favour of #488
