### ISSUE TITLE
BIDS annotations not officially part of BIDS specifications

### ISSUE THREAD

**Issue by laemtl** [aces/Loris-MRI#609]
Annotation files are not part of the specifications yet. Those files do not pass the bids validator if not ignored.
They will also not be loaded by PyBIDS if not specifically included in the BIDSLayout force_index option.
Those hacks can be removed once annotations make their way through the specifications.

The annotation specs are currently discussed in[ BIDS Extension Proposal 21](https://docs.google.com/document/d/1PmcVs7vg7Th-cGC-UrX8rAhKUHIzOI-uIOh69_mvdlw/edit#heading=h.mqkmyp254xh6).

**Comment by cmadjar** [comment]
@laemtl have you tried modifying this file https://github.com/aces/Loris-MRI/blob/main/python/lib/bids.json ?

This is sort of a file that tells pybids the structure of files. I used it in the past for files that were not yet in the BIDS spec officially. 

This file has been created out of https://github.com/bids-standard/pybids/blob/master/bids/layout/config/bids.json which is the config of pybids layout.

**Comment by laemtl** [comment]
@cmadjar Yes I tried to play with it but without any success. I can give it another try if you think it's a better option than force_index.

**Comment by cmadjar** [comment]
@laemtl Maybe give it another try just in case. I could also take a quick look into it as well but if we cannot find any solution via that file, then the force_index option is fine. I guess this issue is related to your PR: https://github.com/aces/Loris-MRI/pull/608

Do you have an example of a dataset with annotation somewhere I could play with?

**Comment by laemtl** [comment]
You can use the 2 files linked in #608!

**Comment by cmadjar** [comment]
@laemtl thank you!

do you also get the following warning from pybids when running bids_import.py?

```
/Users/cmadjar/GitHub/Loris-MRI/venv/lib/python3.9/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
```

Looks like the force_index will be deprecated in future version, and there might also be changes with the config file. Will have to investigate.

**Comment by laemtl** [comment]
@cmadjar Yes I get that too. `ignore`, already in use, will also be deprecated. We can address that in a future PR since we need to upgrade pyBIDS in order to implement the proposed change (the indexer param is not available in PyBIDS 0.11.0)

**Comment by cmadjar** [comment]
@laemtl I was just trying some code in a python terminal for the BIDSLayout to read the annotation files for the following dataset: https://github.com/bids-standard/bids-examples/tree/9893043f52ab1cec144d1b6069497ef48edc9570/eeg_face13

To load the annotations, we need to add a flag to the BIDSLayout command and call the command as follows:
```
bids_layout = BIDSLayout(root='<path_to_eeg_face13>', config=bids_config, ignore=exclude_arr, derivatives=True)
```

The option `derivatives` of the `BIDSLayout()` is by default set to `False` to ignore what is present in the `derivatives` folder. By setting it to `True` when calling `BIDSLayout()`, then it can read the annotation files.

Note: there is a bug in the link above where the command `BIDSLayout` will fail if there is no `dataset_description.json` file in the `derivatives/BIDS-Lossless-EEG` folder and if that file do not contain the following entry:
```
    "PipelineDescription": {
        "Name": "Lossless-EEG"
    }
```

**Comment by laemtl** [comment]
> @laemtl thank you!
> 
> do you also get the following warning from pybids when running bids_import.py?
> 
> ```
> /Users/cmadjar/GitHub/Loris-MRI/venv/lib/python3.9/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
> ```
> 
> Looks like the force_index will be deprecated in future version, and there might also be changes with the config file. Will have to investigate.

Fixed in #627

**Comment by laemtl** [comment]
@Cecile, your solution will work if annotations are stores under a derivatives folder. Mine targets cases where annotations are embedded with raw files.

**Comment by christinerogers** [comment]
Removing stale label since EEGNet changes and community discussions are imminent.  
Note in January 2022 the annotations part of BEP021 was effectively changed to say these will be represented by HED tags, and Jess begin piloting an implementation of HED tags for EEGNet.

**Comment by cmadjar** [comment]
Reopened the issue given comments from Christine and imminent release of BIDS Annotation specs.

**Comment by christinerogers** [comment]
Thanks @cmadjar - I think the actual BEP021 release is not imminent, but on key points there is community alignment and confirmation that is increasingly actionable.
