### ISSUE TITLE
BIDS import : Allow multiple import of candidates

### ISSUE THREAD

**Issue by laemtl** [aces/Loris-MRI#626]
`python3 bids_import.py -d /data/loris-mri/data/bids_files/ -p database_config.py -csv`
The script currently throws an error if participants.tsv already exists in bids_import (bids_file/participants.tsv and bids_import/participants.tsv differ, from copy_file in utilities.py).

As per discussion with Cecile, handle 3 different scenarios:
- [x] candidate not found in participants.tsv -> append it
- [x] candidate found in participants.tsv with no overwrite flag -> display error
- [ ] candidate found in participants.tsv with overwrite flag -> delete data and reimport

**Comment by laemtl** [comment]
@cmadjar Is  it partially fixed by #645?

**Comment by cmadjar** [comment]
@laemtl indeed, the first case is fixed. I also added a column checks to ensure the same columns are present in both participants.tsv files.
