### ISSUE TITLE
[Testing 24.0] - uploadNeuroDB/tarchive_validation.pl

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris-MRI#707]
TODO:
- [ ] run the tarchive_validation.pl script on a valid archive
- [ ] create an empty archive, name it as an existing archive in the DB and run tarchive_validation.pl => this should fail due to different md5

**Comment by CamilleBeau** [comment]
Ran successfully with valid archive. 
Failed successfully with empty archive:
![image](https://user-images.githubusercontent.com/51176779/143902832-5a78a12f-0b12-4e8a-959d-439827529b4c.png)
