### ISSUE TITLE
[Testing 24.0] - dicom_archive/dicomTar.pl and dicom_archive/updateMri_Upload.pl

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris-MRI#709]
TODO:
- [x] run dicomTar.pl without the `-database` flag and ensure nothing gets inserted into the DB
- [x] run dicomTar.pl with the `-database` flag and check that entries got inserted into the DB in the `tarchive*` tables correctly
- [x] run dicomTar.pl with the `-mri_upload_update` flag on a DICOM directory that was not previously uploaded via the imaging uploader (ensure there is nothing in `mri_upload` table for that study before running the script) => ensure that an entry has been added to `mri_upload` for the uploaded DICOM study

**Comment by zaliqarosli** [comment]
https://github.com/aces/Loris-MRI/issues/732
