### ISSUE TITLE
[Testing 24.0] - dicom_archive/get_dicom_info.pl

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris-MRI#710]
- [ ] test the different options of the script and ensure it works as expected

**Comment by jesscall** [comment]
The options `verbose` and `version` are no longer supported by the script and should be removed from the documentation:

https://github.com/aces/Loris-MRI/blob/main/dicom-archive/get_dicom_info.pl#L75-L77

```
Usage: get_dicom_info [options] <dicomfile> [<dicomfile> ...]
       get_dicom_info -help

unknown option: -version

____

Usage: get_dicom_info [options] <dicomfile> [<dicomfile> ...]
       get_dicom_info -help

unknown option: -verbose
