### ISSUE TITLE
Incorrect error for delete_imaging_upload.pl when using -nofilesbk

### ISSUE THREAD

**Issue by thomasbeaudry** [aces/Loris-MRI#798]
When you use the -nofilesbk and you already have the file imaging_upload_backup.tar.gz   then you get the error:
Invalid argument to -backup_path: file imaging_upload_backup.tar.gz already exists. Aborting.
Since you are supplying a flag to ignore backing up files, the script should ignore the fact that a backup file already exists

**Comment by thomasbeaudry** [comment]
If i use both flags, it works

**Comment by cmadjar** [comment]
OK. Then, so technically, this is not a bug. I guess maybe the error displayed could be modified to explain that subtlety though.
