### ISSUE TITLE
Extra '\' in email within prod file

### ISSUE THREAD

**Issue by Jkat** [aces/Loris-MRI#81]
After running the imaging_install.sh script, there is an extra '\' in the email within the generated prod file:

<pre>$mail_user      = "user\@example.com";                        # who will be notified</pre>

The install script seems to purposely do this but is this really intentional? If so, why?
@driusan @mohadesz @cmadjar @samirdas

**Comment by driusan** [comment]
The sed line at the end of the script seems to include ""s#yourname\\\@example.com#$email#g".

So I don't think it's intentional, I think it should be replaced with your email address (which is presumably prompted for earlier in the install script and stored in the $email variable?)

**Comment by Jkat** [comment]
https://github.com/aces/Loris-MRI/blob/master/imaging_install.sh#L51-L52
It doesn't look right to me either, but on those lines it prompts for your email address and then purposely adds a backslash before the '@' symbol.

Unless anyone else has input on this, I will make a pull request for this tomorrow.

**Comment by Jkat** [comment]
Resolved
