### ISSUE TITLE
Add support for additional event data

### ISSUE THREAD

**Issue by laemtl** [aces/Loris-MRI#835]
A praticular project may require to use custom event metadata. We can extend the table `physiological_task_event` with additional columns to support those.
 
- [ ] save all additional event data  present in _events.tsv if a corresponding column exists in `physiological_task_event`. 
- [ ] validate all metadata fields to match the db type.

**Comment by regisoc** [comment]
The table `physiological_task_event` will get all required (base) info, and a new table e.g. `physiological_task_event_opt` should be added to include all optional and added columns in each `_event.tsv`.
