### ISSUE TITLE
HDF5 support (Matlab files) - scipy 

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris-MRI#841]
(placeholder @cmadjar don't hesitate to edit)

Matlab 7.3+ files are not supported by SciPy -  no HDF5 Python library is integrated. 
Loris-MRI has a dependency on SciPy in the pipeline, and it look like it fails on .mat files - likely to impact all projects trying to load .mat data straight out of many EEG suites. 
Since it's not easy (or ideal) to switch out libraries for these functions -- reaching out to SciPy (Nov 2022) is the likely next step. 
There doesn't seem to be any chatter in the SciPy forum/list about this yet. 

reported November 4 by Steven Yeu, Scott Makeig's NEMAR development group, based at UCSD: 

> I updated SciPy to 1.9.3 but still ran into the same error. I was reading the [scipy docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.loadmat.html) and it said that SciPy doesn’t support reading MATLAB 7.3 files. It says a HDF5 Python library is needed to load them and SciPy doesn’t have one. Does that mean the Loris pipeline scripts don’t support this as well?
> 
> I am using Loris-MRI-24.0.2. For Loris, I am using v24.0.3.

**Comment by cmadjar** [comment]
see issue created in the scipy repo for reference: https://github.com/scipy/scipy/issues/17509

**Comment by christinerogers** [comment]
I think JC might have some time to explore this in Jan-Feb since we expect to handle similar (recent matlab) files for EEGNet.  Might be able to quickly contribute a fix to Loris if it's straightforward.

**Comment by christinerogers** [comment]
update (fyi @cmadjar) - in progress at the link below, jc has a fix basically, it's just a question of when/where it should go, cheching for side effects, and having the NEMAR folks test it thoroughly: https://github.com/aces/Loris-MRI/compare/main...jeffersoncasimir:Loris-MRI:hdf5_temporary_solution

**Comment by christinerogers** [comment]
in testing with NEMAR team

**Comment by christinerogers** [comment]
update per MCIN EEG meeting - likely this will be pushed as a little fix on the 24 branch and added in the next bug-fix release.   
Status/priority will be clearer in very early February when we have news on its success from S.Makeig's NEMAR development team.

**Comment by cmadjar** [comment]
@christinerogers @jeffersoncasimir should this be closed?
