### ISSUE TITLE
[BIDS Import] Validate hash  behaviour

### ISSUE THREAD

**Issue by laemtl** [aces/Loris-MRI#894]
For each file, a hash is generated to allow for future data integrity check. At the moment, it seems like the hash function is called on the file path, not the file data.

Example:
https://github.com/aces/Loris-MRI/blob/b9d7ee4f8a8d353673d9e1653855d3a40f5b4a7c/python/lib/eeg.py#L451

Check if this is the case, and correct if necessary.

**Comment by cmadjar** [comment]
Resolved by https://github.com/aces/Loris-MRI/pull/916
