### ISSUE TITLE
[Testing 25.0] tools/delete_imaging_upload.pl

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris-MRI#922]
- [x] Test deletion of an entire MRI upload (UploadID) with SQL and file backup (ensure the SQL and file backup repopulate the database correctly after the deletion) 
  - default file generated, and sourced back without issue.
- [x] Test deletion of an UploadID that has the same TarchiveID as an other UploadID - this should fail with an error message explaining there are multiple UploadID for a given TarchiveID
  - update tarchiveID for an UploadID in table mri_upload with another existing. Run the script, failed.
- [x] Test deletion of an UploadID with QC information attached - this should fail with proper error message
- [x] Test deletion of an UploadID with a parameter_form filled and the option `-form` and ensure the entries in the parameter form have been deleted
- [x] On a defaced dataset, test running the delete script with the `-defaced` option - this should delete only non-defaced MINC files for that UploadID
  - cannot find a defaced dataset. 
- [x] Run the delete script with option `-basename <FileBaseName>` specifying a basename for the MINC files to be deleted - only images matching that basename should be deleted for the UploadID

**Comment by regisoc** [comment]
If executed more than **once** on data that have qc files, the script  will produce a `segmentation fault`.
First occurrence will not have a segmentation fault, but others will.
```bash
# first time
(loris-mri-python) lorisadmin@rongarocarcy-dev:/opt/hbcd/bin/mri$ perl tools/delete_imaging_upload.pl -profile prod -uploadID 62
Cannot delete upload(s) passed on command line: there is QC information defined on the MINC files for the upload IDs passed on the command line

# second
(loris-mri-python) lorisadmin@rongarocarcy-dev:/opt/hbcd/bin/mri$ perl tools/delete_imaging_upload.pl -profile prod -uploadID 62
Cannot delete upload(s) passed on command line: there is QC information defined on the MINC files for the upload IDs passed on the command line
Segmentation fault
```

**Comment by cmadjar** [comment]
> If executed more than **once** on data that have qc files, the script will produce a `segmentation fault`.
> First occurrence will not have a segmentation fault, but others will.

Tested on my local sandbox and cannot reproduce the issue with the delete script. The segmentation fault error is most likely related to trying to delete data from the read-only mount `/data-raisinbread/`. @regisoc will confirm upon further testing.

**Comment by regisoc** [comment]
@cmadjar you should be right on that. I have to make some changes on my vm, so I did not re-tested it yet on it. 
On the test vm, something that also ended with a `segmentation fault` happened with the same script. Mostly related to the `mysqldump` error.

```bash
(loris-mri-python) lorisadmin@test-dev-250:/opt/Loris-MRI/bin/mri$ perl tools/delete_imaging_upload.pl -profile prod -uploadID 138

Backing up files related to the upload(s) to delete...
/data/Loris-MRI/data/assembly/400248/V6/mri/native/Loris-MRI_400248_V6_t1_001.mnc
/data/Loris-MRI/data/assembly/400248/V6/mri/native/Loris-MRI_400248_V6_t1_001.nii.gz
/data/Loris-MRI/data/pic/400248/Loris-MRI_400248_V6_t1_001_447_check.jpg
/data/Loris-MRI/data/tarchive/2016/DCM_2016-08-15_ImagingUpload-16-37-xUKgCm.tar

mysqldump: Couldn't execute 'FLUSH TABLES': Access denied; you need (at least one of) the RELOAD privilege(s) for this operation (1227)
Cannot run command mysqldump  --no-create-info --compact --single-transaction --skip-extended-insert --no-tablespaces --where='ProcessID IN (138)' --result-file=sql_backup_iLG2  -h ace\-db\-2\.cbrain\.mcgill\.ca -pQ3ctTe4n4c82kcfExyy -u test_250_admin test_dev_250 notification_spool 2>&1 | fgrep -v 'mysqldump: [Warning] Using a password on the command line interface can be insecure.'. Aborting
Segmentation fault
```

**Comment by regisoc** [comment]
For the record. `mysqldump: Couldn't execute 'FLUSH TABLES': Access denied;` is because the user accessing db does not have the `RELOAD` privilege. Will be added to the doc.
