### ISSUE TITLE
[Testing 25.0] uploadNeuroDB/imaging_non_minc_insertion.pl

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris-MRI#924]
- [x] ensure that if the following options are not set when running the script, an error is returned: `-file_path`, `-output_type`, `-scan_type`, `-date_acquired`, `-scanner_id`, `-coordin_space`, `-upload_id`
- [x] run the script on a NIfTI file that belongs to a valid UploadID and ensure the file gets inserted into the files table
- [x] check that the `-patient_name` flag works as expected
- [x] check that if a `metadata_file` is provided (example BIDS JSON file), it gets inserted into the parameter_file table and that entries in that metadata file are inserted into parameter_file as well

#986 
#983

**Comment by CamilleBeau** [comment]
When running without naming the file to PSCID_CandID_Visit_label[...], I had the following output: 
`(loris-mri-python) lorisadmin@cbeaudoin-test-25:/opt/Loris-MRI/bin/mri/uploadNeuroDB$ perl imaging_non_minc_insertion.pl -profile prod -file_path '/data/Loris-MRI/data/assembly/400184/V3/mri/native/testing_nifty_file.nii' -output_type native -scan_type dwi25 -date_acquired 2023-06-01 -scanner_id 1 -coordin_space native -upload_id 62
Use of uninitialized value $pscID in string ne at /opt/Loris-MRI/bin/mri/uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm line 1813.
Cannot create visit with project ID 3 and cohort ID 0: no such association in table project_cohort_relsh: 1: cannot create /data/Loris-MRI/data/logs/error.log: Read-only file system
`

Everything with a correctly named file worked as expected.

**Comment by CamilleBeau** [comment]
Issue created #1005
