### ISSUE TITLE
[Testing 25.0] dicom_archive/dicomSummary.pl

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris-MRI#925]
- [ ] test the different options of the script and ensure they work as expected.

**Comment by CamilleBeau** [comment]
I tried modifying some data in the `tarchive` table and then comparing with the dicom using `-dbcompare` argument, but I did not get any results.

`(loris-mri-python) lorisadmin@cbeaudoin-test-25:/opt/Loris-MRI/bin/mri/dicom-archive$ perl dicomSummary.pl /data/Loris-MRI/data/tarchive/2018/ImagingUpload-14-25-U1OlWq -profile prod -dbcompare
(loris-mri-python) lorisadmin@cbeaudoin-test-25:/opt/Loris-MRI/bin/mri/dicom-archive$ `
The data was also not updated with `-dbreplace`. 

There were also no results when comparing 2 different dicom paths. 

`(loris-mri-python) lorisadmin@cbeaudoin-test-25:/opt/Loris-MRI/bin/mri/dicom-archive$ perl dicomSummary.pl /data/Loris-MRI/data/tarchive/2018/ImagingUpload-14-25-U1OlWq -comparedir /data/Loris-MRI/data/tarchive/2018/ImagingUpload-14-30-gRhCrT
(loris-mri-python) lorisadmin@cbeaudoin-test-25:/opt/Loris-MRI/bin/mri/dicom-archive$
`

The rest of the commands seem to be working fine. 

Please let me know if I was doing the testing wrong!

**Comment by CamilleBeau** [comment]
2nd part fixed in #1000
