### ISSUE TITLE
[Testing 25.0] tools/batch_run_pipeline_qc_face_script.pl

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris-MRI#932]
### Test Plan

- [x] Make sure that the command which pipeline_qc_face.pl points to the file in uploadNeuroDB/bin and not the one in the MINC tools

- [x] Create a temporary file called foo that would be creating a file with a date timestamp that you want to use to narrow the find command of the next point 
```
touch --date "2019-01-01" /data/tmp/foo
```

- [x] Run the command below to find defaced files for which a 3D face rendering JPEG image has not been created yet
```
find /data/Loris-MRI/data/assembly -name *defaced* -newer /data/tmp/foo -print > /data/tmp/defaced_list.txt
```

- [x] Run the batch script on the list of files that need to be processed
```
batch_run_pipeline_qc_face_script.pl -profile prod -out_basedir /data/Loris-MRI/data/deface_qc/deface_qc_`date` < /data/tmp/defaced_list.txt
```

### Issues

https://github.com/aces/Loris-MRI/issues/973

**Comment by zaliqarosli** [comment]
works well without QSUB, jpegs created and look good.

Having trouble running with QSUB. apparently QSUB isn't available on Ubuntu 22 (testing VM) https://redmine.cbrain.mcgill.ca/issues/20698. i tried running with slurm (https://www.mankier.com/1/qsub) anyways but the flags/options are a little different so I got an error

**Comment by zaliqarosli** [comment]
@cmadjar john installed OpenPBS and i'm not getting this error:
```
(loris-mri-python) lorisadmin@zrosli-test-25:~$ batch_run_pipeline_qc_face_script.pl -profile prod -out_basedir /data/Loris-MRI/
data/deface_qc/deface_qc_Mon < /data/tmp/defaced_list.txt
Constant subroutine NeuroDB::objectBroker::ConfigOB::CREATE_CANDIDATES redefined at /usr/lib/x86_64-linux-gnu/perl-base/constant
.pm line 171.
option -S is ignored, specify shell via #!<shell> in the job script
Usage:
    qsub [-a start_time] [-A account] [-b y|n] [-e err_path] [-I] [-l
    resource_list] [-m mail_options] [-M user_list] [-N job_name] [-o
    out_path] [-p priority] [-pe shm task_cnt] [-P wckey] [-q destination]
    [-r y|n] [-v variable_list] [-V] [-wd workdir] [-W
    additional_attributes] [-h] [script]
```

i'm not sure exactly where the `#!/bin/sh` should be specified. do you have an idea?

**Comment by laemtl** [comment]
Investigate if QSUB can be replaced with another batching tool. since QSUB is not supported in new version of Ubuntu.
@zaliqarosli Can you add a release note?

**Comment by zaliqarosli** [comment]
"Running batch scripts under tools/ directory with QSUB may fail on Ubuntu 22. To fix this, turn off the is_qsub configuration by setting the Project batch management used config to 'No' under the Imaging Pipeline tab of the Configuration module." added to Release notes under "Notes for Existing Projects" - Notable non-SQL changes
