### ISSUE TITLE
[Testing 25.0] tools/get_dicom_files.pl

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris-MRI#937]
Valid usage tested:
- [x] name: one name, multiple names
- [x] type: one type, mutliple types
- [x] outdir: /data/tmp
- [x] outfile: a new name
- [x] id: pscid, candid, pscid_candid or candid_pscid
- [x] profile: prod

Errors tested:
- [x] no name and no type
- [x] no profile
- [x] 1 wrong name
- [x] 2 wrong names
- [x] 1 wrong type
- [x] 2 wrong types
- [x] wrong profile
- [x] wrong id 
- [x] Non-existent outdir 

Expected default values:
- [x] no id -> candid
- [x] no outdir -> env TMPDIR (`/data/tmp`)
- [x] no outfile -> current folder, dicoms.tar.gz
- [x] no type -> all types for selected 1 name
- [x] no type -> all types for selected 2 names
- [x] no name -> all name for selected 1 type
- [x] no name -> all name for selected 2 types

Some nominal usages (profile + ...):
- [x] 1 name + 1 type
- [x] 1 name + 2 types
- [x] 2 names + 1 type
- [x] 2 names + 2 types
- [x] 1 good name + 1 wrong name (should ignore the wrong one, order does not matter)
- [x] 1 good type + 1 wrong type (should ignore the wrong one, order does not matter)
- [x] 1 name+ 1 type + candid (default, but explicit)
- [x] 1 name+ 1 type + pscid
- [x] 1 name+ 1 type + pscid_candid
- [x] 1 name+ 1 type + candid_pscid

Minor issue: #1008 
Known issue not fixed in this release: #718

**Comment by regisoc** [comment]
Parameters tested:
- name: one name, multiple names
- type: one type, mutliple types
- outdir: /data/tmp
- outfile: a new name
- id: pscid, candid, pscid_candid or candid_pscid
- profile: prod

Expected error tested:
- [x] no name and no type
- [x] no profile
- [x] 1 wrong name
- [x] 2 wrong names
- [x] 1 wrong type
- [x] 2 wrong types
- [x] wrong profile
- [ ] wrong id -> @cmajdar found something fishy

```bash
# watch the -id parameter

# this does not work -> ok
perl tools/get_dicom_files.pl -name DCC090_587630_V1 -type dwi25 -outfile test -id nope -profile prod

# this works -> should not. `.tar.gz` created ignoring the ID folder, only visit folder. 
perl tools/get_dicom_files.pl -name DCC090_587630_V1 -type dwi25 -outfile test -id candidididi -profile prod
perl tools/get_dicom_files.pl -name DCC090_587630_V1 -type dwi25 -outfile test -id pscidididi -profile prod

# One user + one type seems fine, but if multiple names that have the same visit => mixed in the same visit folder.
perl tools/get_dicom_files.pl -name DCC090_587630_V1,DCC292_676061_V1 -type t1 -outfile test -id candididi -profile prod
```

Could change that behaviour here: 
https://github.com/aces/Loris-MRI/blob/033d15074d2146ac376a2fff04dee388d18c277a/tools/get_dicom_files.pl#L393

Expected default values:
- [x] no id -> candid
- [x] no outdir -> env TMPDIR (`/data/tmp`)
- [x] no outfile -> current folder, dicoms.tar.gz
- [x] no type -> all types for selected 1 name
- [x] no type -> all types for selected 2 names
- [x] no name -> all name for selected 1 type
- [x] no name -> all name for selected 2 types

Some nominal usages (profile + ...):
- [x] 1 name + 1 type
- [x] 1 name + 2 types
- [x] 2 names + 1 type
- [x] 2 names + 2 types
- [x] 1 good name + 1 wrong name (should ignore the wrong one, order does not matter)
- [ ] 1 good type + 1 wrong type (should ignore the wrong one, order does not matter)
- [ ] 1 name+ 1 type + candid (default, but explicit)
- [ ] 1 name+ 1 type + pscid
- [ ] 1 name+ 1 type + pscid_candid
- [ ] 1 name+ 1 type + candid_pscid

**Comment by regisoc** [comment]
@cmadjar only one point for this script, else LGTM
