### ISSUE TITLE
[Testing 25.0] tools/seriesuid2fileid.pl

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris-MRI#944]
Test:
- [x] no param -> help
- [x] wrong prod file -> error
- [x] wrong uid -> nothing printed
- [x] empty uid -> nothing printed
- [ ] empty space before good uid -> do not find the info -> @cmadjar is this behaviour expected?
- [x] empty space after good uid -> ok

LGTM else.

**Comment by regisoc** [comment]
Test:
- [x] no param -> help
- [x] wrong prod file -> error
- [x] wrong uid -> nothing printed
- [x] empty uid -> nothing printed
- [ ] empty space before good uid -> do not find the info -> @cmadjar is this behaviour expected?
- [x] empty space after good uid -> ok

LGTM else.
