### ISSUE TITLE
[bids_import] Images not found after import

### ISSUE THREAD

**Issue by jeffersoncasimir** [aces/Loris-MRI#969]
While testing `bids_import.py` (#923), I encountered an issue with MRI.

I imported [this dataset](https://openneuro.org/datasets/ds004560/versions/1.0.1) and it ran without errors. However, the following warning appeared: `/opt/eegnet/bin/mri/python_virtualenvs/loris-mri-python/lib/python3.6/site-packages/nilearn/image/resampling.py:531: UserWarning: Casting data from int32 to float32 warnings.warn("Casting data from %s to %s" % (data.dtype.name, aux))`

After selecting `native` for example from the session browser, the session viewer loads with broken thumbnails, shown below
<img width="1196" alt="Screenshot 2023-05-02 at 2 20 23 PM" src="https://user-images.githubusercontent.com/15801528/235752261-aaabf353-0f7f-4de8-97a5-0bcbd9fbf759.png">

When clicking a thumbnail, it loads `/brainbrowser/?minc_id=[:id]` and shows the message below:
<img width="1398" alt="Screenshot 2023-05-02 at 2 20 43 PM" src="https://user-images.githubusercontent.com/15801528/235752529-51e0aeb6-f129-4b53-8421-6585329ff43c.png">

There are no errors in the server log either.

**Comment by cmadjar** [comment]
@jeffersoncasimir what are the permissions of those files on the filesystem? Can they be read by apache? Are they located on the filesystem and can you open them outside of LORIS?

**Comment by jeffersoncasimir** [comment]
@cmadjar I just changed ownership to lorisadmin:www-data and tried without success with 777 permissions. The .nii files are on the filesystem and I downloaded one and I am able to view it and interact with it using this: https://socr.umich.edu/HTML5/BrainViewer/

**Comment by jeffersoncasimir** [comment]
I ran the same dataset with the test-25 VM and it works as expected. It appears to be an issue with my other VMs environment.

**Comment by jeffersoncasimir** [comment]
Please close this if you think it is no longer relevant.
